import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Senai Website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <p className="text-5xl text-cyan-900">Senai-Website</p>
        <ul className="list-disc p-10 text-xl">
          <li className="">Conectar com o Firebase</li>
        </ul>
      </main>
    </div>
  )
}
