import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import type { NextPage } from 'next'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Senai Website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <p className="text-5xl text-cyan-900">Nextjs + Typescript + Tailwindcss Template</p>
        <ul className="list-disc p-10 text-xl">
          <li className="">Just do it.</li>
        </ul>
      </main>
    </div>
  )
}

export default Home